import React,{useEffect,useState} from 'react';
import { C,Card,Big,Pill,Mono } from '../lib/ui.jsx';
import { dateInDublin } from '../lib/editorial-calendar.js';

export default function Followups(){
  const [data,setData]=useState(null),[sync,setSync]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('open');
  const source=new URLSearchParams(location.search).get('source');
  async function request(input){setBusy(true);try{const r=await fetch('/api/followups',{credentials:'same-origin',...(input?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error || 'Could not load follow-ups');setData(d.data);if(d.sync)setSync(d.sync);setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{request();},[]);
  const today=dateInDublin();
  const actions=(data?.actions || []).filter(a=>(view==='all'||a.state==='open')&&(!source||a.sourceId===source)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  return <div><p>The morning email prepares today. The evening email captures today’s promises. Call and email actions are grouped by due date, with their original evidence.</p>
    <Card style={{marginBottom:16}}><Mono>Daily · 09:30 and 20:30 · Ireland</Mono><p>Actions from each email are imported automatically, normally within 15 minutes. Reviewing a link never sends or approves anything.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Pill sm disabled={busy} onClick={()=>request({action:'sync'})}>Import latest email</Pill><Pill sm tone="ghost" onClick={()=>setView(view==='open'?'all':'open')}>{view==='open'?'Include completed':'Show open only'}</Pill>{source&&<a href="/?room=followups">All follow-ups</a>}</div>{sync?.at&&<p style={{fontSize:12}}>Last import check: {new Date(sync.at).toLocaleString('en-IE',{timeZone:'Europe/Dublin'})}</p>}{(sync?.error || sync?.errors?.length>0)&&<p role="alert" style={{color:C.red}}>Import needs attention: {sync.error || sync.errors.map(e=>e.error).join('; ')}</p>}</Card>
    {error&&<p role="alert" style={{color:C.red}}>{error}</p>}
    {!data?<p>Loading follow-ups…</p>:!actions.length?<Card>No matching actions imported yet. The first review is scheduled for this evening; late transcripts are picked up by the next review.</Card>:actions.map((a,i)=><React.Fragment key={a.id}>{(i===0||actions[i-1].dueDate!==a.dueDate)&&<div style={{margin:'22px 0 10px'}}><Big s={22}>{a.dueDate}{a.dueDate<today?' · OVERDUE':a.dueDate===today?' · TODAY':''}</Big></div>}<Card style={{marginBottom:12}}><Mono>{a.owner} · {a.state} · {a.sourceType}</Mono><h3 style={{fontSize:18,margin:'10px 0'}}>{a.title}</h3><p style={{fontSize:13}}>Due {a.dueDate} · {a.dueBasis==='proposed'?'PROPOSED — confirm the date':'Agreed / confirmed'}</p><blockquote style={{fontSize:13,margin:'10px 0',borderLeft:'3px solid '+C.ink,paddingLeft:12}}>{a.evidence}</blockquote>{a.draft&&<details><summary>Review follow-up draft</summary><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",fontSize:14}}>{a.draft}</pre><Pill sm tone="ghost" onClick={()=>navigator.clipboard?.writeText(a.draft)}>Copy draft</Pill></details>}{a.sourceUrl&&<a href={a.sourceUrl} target="_blank" rel="noreferrer">Review source</a>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}>{a.dueBasis==='proposed'&&<Pill sm disabled={busy} tone="ghost" onClick={()=>request({id:a.id,action:'due',date:a.dueDate})}>Confirm proposed date</Pill>}{a.state==='open'?<><Pill sm disabled={busy} onClick={()=>request({id:a.id,action:'done'})}>Mark done</Pill><Pill sm disabled={busy} tone="ghost" onClick={()=>request({id:a.id,action:'dismissed'})}>Dismiss</Pill></>:<Pill sm disabled={busy} onClick={()=>request({id:a.id,action:'open'})}>Reopen</Pill>}<label style={{fontSize:12}}>Set / confirm due date <input aria-label={'Due date for '+a.title} type="date" defaultValue={a.dueDate} disabled={busy} onChange={e=>{if(e.target.value)request({id:a.id,action:'due',date:e.target.value});}}/></label></div></Card></React.Fragment>)}
    <details style={{marginTop:22}}><summary>Transcript reviews, including calls with no actions</summary>{(data?.reviews || []).filter(r=>!source||r.sourceId===source).map(r=><Card key={r.sourceId} style={{marginTop:12}}><strong>{r.title}</strong><p style={{fontSize:13}}>{r.summary}</p><Mono>{r.sourceDate} · reviewed {r.reviewedAt}</Mono>{r.sourceUrl&&<p><a href={r.sourceUrl} target="_blank" rel="noreferrer">Open transcript</a></p>}</Card>)}</details>
  </div>;
}
